export const POKEMON_CONFIG = {
    URL_EN: "https://www.pokemon.com/us/pokemon-tcg/pokemon-cards",
    URL_TCG_EN: "https://www.tcgplayer.com/search/pokemon/product?productLineName=pokemon&view=grid",

    URL_JP: "https://www.tcgplayer.com/search/pokemon-japan/product?productLineName=pokemon-japan&view=grid&ProductTypeName=Cards",
    URL_TH: "https://asia.pokemon-card.com/th/card-search/",
    RARITY_MAP: {
        Common: "C",
        "Common Holo": "C",
        Uncommon: "U",
        "Uncommon Holo": "U",
        Rare: "R",
        "Rare Holo": "R",
        "Rare Holo V": "RV",
        "Rare Holo VMAX": "RVX",
        "Rare Holo VSTAR": "RVS",
        "Rare Holo EX": "REX",
        "Rare Holo GX": "RGX",
        "Rare Ultra": "RU",
        "Rare Secret": "RS",
        "Rare Rainbow": "RR",
        "Illustration Rare": "IR",
        "Special Illustration Rare": "SIR",
        "Double Rare": "DR",
        "Hyper Rare": "HR",
        Promo: "P",
    } as Record<string, string>,
    SET_MAP: {
        MEW: "sv3pt5",
        ASC: "me2pt5",
    } as Record<string, string>,
    SET_MAP_TCG_PLAYER: {
        "sv-scarlet-and-violet-151": "sv3pt5",
        "me-ascended-heroes": "me2pt5",
    } as Record<string, string>,
};
